//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliverinfo
    {
        public int Id { get; set; }
        public int O_id { get; set; }
        public string D_username { get; set; }
        public string D_statue { get; set; }
        public string D_time { get; set; }
    
        public virtual myorder myorder { get; set; }
    }
}
