//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Systemuser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Systemuser()
        {
            this.myorders = new HashSet<myorder>();
            this.Tokens = new HashSet<Token>();
        }
    
        public int Id { get; set; }
        public string U_name { get; set; }
        public string U_phone { get; set; }
        public string U_address { get; set; }
        public string U_username { get; set; }
        public string U_email { get; set; }
        public string U_password { get; set; }
        public string Usertype { get; set; }
        public string U_profileimg { get; set; }
        public string pharmacyname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<myorder> myorders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Token> Tokens { get; set; }
    }
}
